### ISSUE TITLE
Mask Decoder

### ISSUE THREAD

**Issue by alany-dev** [aswahd/SamRadiology#4]
Hello, thank you very much for your work. I am puzzled by the processing in the mask_encoder. The code stacks the image_embedding along dimension 0 by the number of categories, and I speculate that the purpose is to segment each class for every image. However, when the mask_encoder segments different masks for the same image, the output uses the same layer's computation results, which is different from MedSAM and SAM-Med2D, as they use different layers to be responsible for the mask prediction of different categories. Perhaps my understanding is incorrect, please correct me if I am wrong. Thank you.

**Comment by aswahd** [comment]
Hi @star-cs, 

In Sam2Rad, the same `mask_token` is used for all classes, meaning the mask decoder is not aware of the different classes. Instead, each class is associated with a distinct set of queries. These queries, with a shape of `(C x N x D)` (where `C` is the number of classes, `N` is the size of the queries, and `D` is the channel dimension), are utilized by the prompt generator to create class-specific prompts. In fact, we do not modify SAM's architecture (image encoder, prompt encoder, and mask decoder). Instead, we add a prompt generator to augment the prompt encoder. So, you can use MedSAM or SAM-Med2D as a replacement for SAM, and SAM2Rad would still generate the prompts. 

As you mentioned, the input images are repeated to match the number of classes. 

I hope this explains it  
https://github.com/aswahd/SamRadiology/blob/ccf881d3faf12e733dcb852c07329431c45fc4d4/sam2rad/models/sam2rad/model.py#L249-L255

**Comment by alany-dev** [comment]
Thank you very much for your explanation, I think I should understand now.
